#define ACTION_TURN_IN_SPOT_LEFT '1'
#define ACTION_GO_BACK '2'
#define ACTION_TURN_IN_SPOT_RIGHT '3'
#define ACTION_SHIFT_LEFT '4'
#define ACTION_STOP '5'
#define ACTION_SHIFT_RIGHT '6'
#define ACTION_TURN_LEFT '7'
#define ACTION_GO_ADVANCE '8'
#define ACTION_TURN_RIGHT '9'
#define ACTION_ALIGN_HEAD '*'
#define ACTION_ECHO_SCAN '-'
#define ACTION_SCAN_DIRECTION '+'
#define ACTION_WATCH 'W'
#define ACTION_TEST 'T'

#define INTERACTION_BEGIN 1
#define INTERACTION_ONGOING 2
#define INTERACTION_TERMINATE 3
#define INTERACTION_SEND 4
#define INTERACTION_DONE 5

#define DIRECTION_FRONT 0
#define DIRECTION_LEFT 1
#define DIRECTION_BACK 2
#define DIRECTION_RIGHT 3
